config/routes.rb
DruggableGene::Application.routes.draw do
  get 'interactions/:id' => 'interactions#show', constraints: { name: /[^\/]+/ }
  get 'gene_claims/:source_db_name/:name' => 'gene_claims#show'
  get 'drug_claims/:source_db_name/:name' => 'drug_claims#show'
  get 'gene_names' => 'genes#names'
  # add a drug_names thing here, so that they can be pulled via json?
  get 'drug_names' => 'drugs#names'
  get 'genes/:name' => 'genes#show', as: 'gene'
  get 'interaction_claims/:id' => 'interaction_claims#show', as: 'interaction_claims'
  get 'druggable_gene_categories/:name' => 'genes#druggable_gene_category', as: 'gene_by_category'
  get 'druggable_gene_categories' => 'genes#druggable_gene_categories'
  get 'drugs/:name' => 'drugs#show', as: 'drug', name: /.*/
  get 'sources/:source_db_name' => 'sources#show', as: 'source'
  get 'sources' => 'sources#sources'
  get 'search_results' => 'search#search_results'
  get 'cache/invalidate' => 'utilities#invalidate_cache'
  post  'download_table' => 'utilities#download_request_content'
  scope 'api' do
    scope 'v1' do
      post  'interactions' => 'services_v1#interactions'
      post  'related_genes' => 'services_v1#related_genes'
      get   ':action' => 'services_v1#:action'
    end
    scope 'v2' do
      post  'interactions' => 'services_v2#interactions'
      post  'related_genes' => 'services_v2#related_genes'
      get   ':action' => 'services_v2#:action'
      get   'genes/:entrez_id' => 'services_v2#gene_details'
      get   'drugs/:chembl_id' => 'services_v2#drug_details'
      get   'interactions/:id' => 'services_v2#interaction_details'
    end
  end
  match 'interaction_search_results/:name' => 'interaction_claims#interaction_search_results', name: /.*[^#]/, via: [:get, :post]
  match 'interaction_search_results' => 'interaction_claims#interaction_search_results', via: [:get, :post]
  match 'interactions_for_related_genes' => 'interaction_claims#interactions_for_related_genes', via: [:get, :post]
  match 'categories_search_results' => 'genes#categories_search_results', via: [:get, :post]
  get ':action' => 'static#:action'
  root :to => 'static#home'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_results
    validate_search_request(params)
    @search_results = Search.search(params[:search_term])
  end

  private
  def validate_search_request(params)
    bad_request("Please enter a search term!") if params[:search_term].blank?
  end

end

app/views/search/_drug_claim_alias_search_result.html.haml
.well
  %em Drug Claim Alias
  %p
    %strong=link_to r.alias, drug_claim_path(r.drug_claim)
    %p="Drug Claim:  #{r.drug_claim.name} from #{r.drug_claim.source.source_db_name} version #{r.drug_claim.source.source_db_version}"

app/views/search/_drug_claim_search_result.haml
.well
  %em Drug Claim
  %p
    %strong=link_to r.name, drug_claim_path(r)
    %p="Source:  #{r.source.source_db_name} version #{r.source.source_db_version}"

app/views/search/_drug_search_result.html.haml
.well
  %em Drug
  %p
    %strong=link_to r.name , drug_path(r.name)
    %p="Drug Claims:  #{r.drug_claims.count}"

app/views/search/_gene_claim_alias_search_result.html.haml
.well
  %em Gene Claim Alias
  %p
    %strong=link_to r.alias, gene_claim_path(r.gene_claim)
    %p="Gene:  #{r.gene_claim.name} from #{r.gene_claim.source.source_db_name} version #{r.gene_claim.source.source_db_version}"

app/views/search/_gene_claim_search_result.html.haml
.well
  %em Gene Claim
  %p
    %strong=link_to r.name, gene_claim_path(r)
    %p="Source:  #{r.source.source_db_name} version #{r.source.source_db_version}"

app/views/search/_gene_search_result.html.haml
.well
  %em Gene
  %p
    %strong=link_to r.name, gene_path(r.name)
    %p="Gene Claims:  #{r.gene_claims.count}"

app/views/search/search_results.html.haml
#notice= notice
=content_for :title do
  =tx "title"
=content_for :header do
  %h2
    =tx "title_main"
    %small=tx "title_small"

.row-fluid.span12
  .span6
    -@search_results.each do |result|
      =result.render_result(self)