config/routes.rb
DruggableGene::Application.routes.draw do
  get 'interactions/:id' => 'interactions#show', constraints: { name: /[^\/]+/ }
  get 'gene_claims/:source_db_name/:name' => 'gene_claims#show'
  get 'drug_claims/:source_db_name/:name' => 'drug_claims#show'
  get 'gene_names' => 'genes#names'
  # add a drug_names thing here, so that they can be pulled via json?
  get 'drug_names' => 'drugs#names'
  get 'genes/:name' => 'genes#show', as: 'gene'
  get 'interaction_claims/:id' => 'interaction_claims#show', as: 'interaction_claims'
  get 'druggable_gene_categories/:name' => 'genes#druggable_gene_category', as: 'gene_by_category'
  get 'druggable_gene_categories' => 'genes#druggable_gene_categories'
  get 'drugs/:name' => 'drugs#show', as: 'drug', name: /.*/
  get 'sources/:source_db_name' => 'sources#show', as: 'source'
  get 'sources' => 'sources#sources'
  get 'search_results' => 'search#search_results'
  get 'cache/invalidate' => 'utilities#invalidate_cache'
  post  'download_table' => 'utilities#download_request_content'
  scope 'api' do
    scope 'v1' do
      post  'interactions' => 'services_v1#interactions'
      post  'related_genes' => 'services_v1#related_genes'
      get   ':action' => 'services_v1#:action'
    end
    scope 'v2' do
      post  'interactions' => 'services_v2#interactions'
      post  'related_genes' => 'services_v2#related_genes'
      get   ':action' => 'services_v2#:action'
      get   'genes/:entrez_id' => 'services_v2#gene_details'
      get   'drugs/:chembl_id' => 'services_v2#drug_details'
      get   'interactions/:id' => 'services_v2#interaction_details'
    end
  end
  match 'interaction_search_results/:name' => 'interaction_claims#interaction_search_results', name: /.*[^#]/, via: [:get, :post]
  match 'interaction_search_results' => 'interaction_claims#interaction_search_results', via: [:get, :post]
  match 'interactions_for_related_genes' => 'interaction_claims#interactions_for_related_genes', via: [:get, :post]
  match 'categories_search_results' => 'genes#categories_search_results', via: [:get, :post]
  get ':action' => 'static#:action'
  root :to => 'static#home'
end

app/models/data_model/interaction_claim.rb
module DataModel
  class InteractionClaim < ::ActiveRecord::Base
    include Genome::Extensions::UUIDPrimaryKey

    has_many :interaction_claim_attributes, inverse_of: :interaction_claim
    belongs_to :gene_claim, inverse_of: :interaction_claims
    belongs_to :drug_claim, inverse_of: :interaction_claims
    belongs_to :source, inverse_of: :interaction_claims, counter_cache: true
    has_and_belongs_to_many :interaction_claim_types, :join_table => 'interaction_claim_types_interaction_claims'
    belongs_to :interaction
    has_and_belongs_to_many :publications

    def self.for_show
      eager_load(:interaction_claim_types, :interaction_claim_attributes, :source, :drug_claim, gene_claim: [:gene, :source])
    end

    def self.for_tsv
      includes(:source, :interaction_claim_types, :publications, drug_claim: [:drug], gene_claim: [:gene])
    end

    def drug
      self.drug_claim.drug
    end

    def gene
      self.gene_claim.gene
    end
  end
end

app/models/data_model/interaction_claim_type.rb
module DataModel
  class InteractionClaimType < ::ActiveRecord::Base
    include Genome::Extensions::UUIDPrimaryKey
    include Genome::Extensions::EnumerableType
    include Genome::Extensions::HasCacheableQuery

    has_and_belongs_to_many :interaction_claims, :join_table => 'interaction_claim_types_interaction_claims'

    cache_query :all_type_names, :all_interaction_type_names

    def self.all_type_names
      pluck(:type).sort
    end

    private
    def self.enumerable_cache_key
      'all_interaction_claim_types'
    end
  end
end

app/controllers/interaction_claims_controller.rb
class InteractionClaimsController < ApplicationController
  def show
    @interaction_claim = InteractionClaimPresenter.new(
      DataModel::InteractionClaim.for_show.find(params[:id]))
  end

  def interaction_search_results
    if !params[:name].nil?
      params[:search_mode] = 'drugs'
      params[:identifiers] = params[:name]
      params[:gene_categories] = DataModel::GeneClaimCategory.all_category_names unless params[:gene_categories]
      params[:sources] = DataModel::Source.potentially_druggable_source_names unless params[:sources]
      params[:source_trust_levels] = DataModel::SourceTrustLevel.all_trust_levels unless params[:source_trust_levels]
    end
    @search_interactions_active = 'active'
    @search_mode = params[:search_mode]
    if @search_mode == 'drugs'
      params[:drugs] = params[:identifiers]
      combine_input_drugs(params)
    elsif @search_mode == 'genes'
      params[:genes] = params[:identifiers]
      combine_input_genes(params)
    else
      if params[:genes]
        combine_input_genes(params)
      elsif params[:drugs]
        combine_input_drugs(params)
      end
    end
    @view_context = view_context
    unpack_locals(params)
    perform_interaction_search
    prepare_export
  end

  def interactions_for_related_genes
    @related_source_gene = params[:genes]
    combine_input_genes(params)
    related_genes = LookupRelatedGenes.find(params[:gene_names])
    if related_genes.empty?
      not_found("Sorry, we don't have any genes related to #{@related_source_gene}")
    end
    params[:gene_names] = related_genes.flat_map(&:gene_gene_interaction_claims)
      .map { |ic| ic.interacting_gene.name }
    perform_interaction_search
    render :interaction_search_results
  end

  private
  def perform_interaction_search
    validate_interaction_request(params)
    search_results = LookupInteractions.find(params)
    @search_results = InteractionSearchResultsPresenter.new(search_results, view_context)
  end

  def unpack_locals(params)
    @preset_fda = (params[:fda_approved_drug] == "checked" ? "FDA Approved" : "")
    @preset_neo = (params[:anti_neoplastic] == "checked" ? "Anti-neoplastics" : "")
    @preset_immuno = (params[:immunotherapy] == "checked" ? "Immunotherapies" : "")
    @preset_clin = (params[:clinically_actionable] == "checked" ? "Clinically Actionable" : "")
    @preset_druggable = (params[:druggable_genome] == "checked" ? "Druggable Genome" : "")
    @preset_resist = (params[:drug_resistance] == "checked" ? "Drug Resistance" : "")
  end

  def prepare_export(compound_field_separator = '|')
    headers = %w[search_term match_term match_type gene drug interaction_types sources pmids]
    @tsv = CSV.generate(col_sep: "\t") do |tsv|
      tsv << headers
      @search_results.search_results.each do |result|
        row_hash = {
            'match_type' => result.match_type_label,
            'search_term' => result.search_term
        }
        result.interactions.each do |identifier, interactions|
          row_hash['match_term'] = identifier.name
          interactions.each do |interaction|
            row_hash['gene'] = interaction.gene.name
            row_hash['drug'] = interaction.drug.name
            row_hash['interaction_types'] = interaction.type_names.join(compound_field_separator)
            row_hash['pmids'] = interaction.pmids.join(compound_field_separator)
            row_hash['sources'] = interaction.source_names.join(compound_field_separator)
            tsv << headers.map{ |field| row_hash[field] }
          end
        end
      end
    end
  end
end

app/views/interaction_claims/_interaction_claim.html.haml
- cache interaction_claim do
  - interaction = interaction_claim.interaction
  .container-fluid
    .tabbable
      .tab-content
        .tab-pane.active#summary
          .row-fluid#container 
            .span12
              %ul(class="result-list" id="list-results")
                %li.interaction
                  %div(class="item-title")
                    %div(class="item-name")
                      %h3(class="item-source")
                        =succeed ':' do
                          =link_to interaction_claim.source.source_db_name, source_path(interaction_claim.source.source_db_name)
                        %a{href: "/drugs/#{interaction.drug.name}"} 
                          =interaction.drug.name
                        %span{class: "glyphicon glyphicon-play", "aria-hidden" => "true", style: "margin-left: 10px; margin-right: -8px"}
                        &nbsp
                        %a{href: "/genes/#{interaction.gene.name}"} 
                          =interaction.gene.name 
                    %div(class="item-corner")
                      %ul(class="attribute-list")
                        %li
                          %strong
                            Version:
                          =interaction_claim.source.source_db_version
                        
                  %div(class="item-content")
                    %div{class: "cell category", style: "float: left; width: 50%" }
                      %div{class: "item-panel", style:"margin-bottom: 10px"}
                        %h4
                          Main Info:
                        %div{style: "height: 90px; overflow-y: scroll; margin-bottom: 5px;"}
                          %table{class: "table table-condensed table-striped", id: "table_main"}
                            %tr
                              %td{style: "width: 30%"}="Gene"
                              %td{style: "width: 70%"}
                                %a{href: "/genes/#{interaction.gene.name}"} 
                                  =interaction.gene.name
                            %tr
                              %td="Drug"
                              %td
                                %a{href: "/drugs/#{interaction.drug.name}"} 
                                  =interaction.drug.name
                            %tr
                              %td="interaction_claim Types"
                              %td=interaction_claim.interaction_claim_types.map{|it| it.type}.join(", ")
                      %div(class="item-panel")
                        %h4
                          Publications:
                        %div{style: "height: 305px; overflow-y: scroll; "}
                          %table{class: "table table-condensed table-striped", id:"table_publications"}
                            -interaction_claim.publications.each do |publication|
                              %tr
                                %td
                                  %a{href: PMID.pubmed_url(publication.pmid)}
                                    = publication.citation
                    %div{class: "cell category", style: "float: right; width: 50%"}
                      %div(class="item-panel")
                        %h4
                          Other Info:
                        %div{style: "height: 456px; overflow-y: scroll; "}
                          %table{class: "table table-condensed table-striped", id: "table_info"}
                            -interaction_claim.interaction_claim_attributes.each do |attribute|
                              %tr
                                %td{style: "width: 300px"}=attribute.name
                                %td{style: "width: 350px"}=attribute.value

app/views/interaction_claims/_interaction_claim_summary.html.haml
- cache interaction_claim do
  -interaction = interaction_claim.interaction
  %div(class="item-title")
    %div(class="item-name")
      %h3(class="item-source")
        =succeed ':' do
          =link_to interaction_claim.source.source_db_name, source_path(interaction_claim.source.source_db_name)
        %a{href: "/drugs/#{interaction.drug.name}"} 
          =interaction.drug.name
        %span{class: "glyphicon glyphicon-play", "aria-hidden" => "true", style: "margin-left: 10px; margin-right: -8px"}
        &nbsp
        %a{href: "/genes/#{interaction.gene.name}"} 
          =interaction.gene.name 
    %div(class="item-corner")
      %ul(class="attribute-list")
        %li
          %strong
            Version:
          =interaction_claim.source.source_db_version

%div(class="item-content")
  %div(class="cell category")
    %div(class="item-panel")
      %h4{style: "display: inline-block;"}
        Main Info:
        %table{class: "table table-condensed table-striped", style: "table-layout:fixed;" }
          %tr
            %td="Gene"
            %td=@interaction.gene.name
          %tr
            %td="Drug"
            %td=@interaction.drug.name
          %tr
            %td="Interaction Types"
            %td=interaction_claim.interaction_claim_types.map{|ict| ict.type}.join(", ")

  %div(class="cell category")
    %div(class="item-panel")
      %h4
        Other Info:
        %table{class: "table table-condensed table-striped", style: "table-layout:fixed;" }
          -interaction_claim.interaction_claim_attributes[0..2].each do |attribute|
            %tr
              %td=attribute.name
              %td=attribute.value

  %div(class="cell category")
    %div(class="item-panel")
      %h4
        Publications:
        %table{class: "table table-condensed table-striped", style: "table-layout:fixed;" }
          -interaction_claim.publications[0..2].each do |publication|
            %tr
              %td
                %a{href: PMID.pubmed_url(publication.pmid)}
                  = publication.citation

app/views/interaction_claims/_interaction_search_failed.html.haml
- ambiguous_matches = ambiguous_results + ambiguous_no_interactions
%div{style: "float: right; margin-top: -15px; width: 20%"}
  = render partial: 'shared/page_export'
  %div.well{style: "margin-top: 15px;"}
    %h3{style: "margin-top: -5px;"}
      Unmatched Terms
    - failed_terms.each do |term|
      %li
        = term

  %div.well{style: "margin-top: -5px;"}
    %h3{style: "margin-top: -5px; margin-bottom: -5px;"}
      Multiple Matches
    %div{style: "width: 200px; padding: 0", class: "container demo"}
    - if ambiguous_matches.count > 0
      %div(class="panel-group" id="accordion" role="tablist" aria-multiselectable="true")
        - ambiguous_matches.each do |result|
          %ul{class: "tree", style: "margin-left: -15px;"}
            %li
              %input{type: "checkbox", checked: "checked", id: "#{'heading' + result[:term]}"}
              %label{for: "#{'heading' + result[:term]}", class: "tree_label"}
                %span
                  %input{class: "ambiguous search-term", type: "checkbox", name: result[:term], checked: 1}
                    = result[:term]
              %ul
                - result[:identifiers].each do |entity|
                  %li
                    %span{class: "tree_label"}
                      %input{class: "ambiguous sidebar-toggle #{result[:term]}", type: "checkbox", name: "#{entity.name + "-ambiguous"}", checked: 1}
                        = entity.name 
    - else
      %div{style: "margin-top:15px;"}
        %i
          None found.
%div{style: "float: left; width: 78%;"}
  %ul(class="result-list" id="list-results")
    - if ambiguous_matches.count > 0
      - ambiguous_matches.each do |result|
        - result[:identifiers].each do |entity|
          %li{class: "interaction interaction-panel", "data-category" => "interaction", "data-name" => "Interaction", id: entity.name + "-ambiguous", style: "display: list-item; width: 100%;"}
            = render partial: 'interaction_claims/interactions_search_panel', locals: { term: result[:term], entity: entity, filtered_interactions: result[:interactions][entity].to_a }
    - else 
      %li{class: "interaction interaction-panel", "data-category" => "interaction", "data-name" => "Interaction", style: "width: 100%; height: 300px;"}
        %h3{style: "margin-left: 20px;"}
          None of your search terms returned 
          %i 
            ambiguous 
          matches.
          
:css
  /* ————————————————————–
    Tree core styles
  */
  .tree { margin: 1em; }

  .tree input {
    position: absolute;
    clip: rect(0, 0, 0, 0);
    }

  .tree input ~ ul { display: none; }

  .tree input:checked ~ ul { display: block; }

  /* ————————————————————–
    Tree rows
  */
  .tree li {
    line-height: 1.2;
    position: relative;
    padding: 0 0 1em 1em;
  }

  .tree ul li { padding: 1em 0 0 1em; }

  .tree ul { padding-left: 0; margin: -5px 0 0 -2px; }

  .tree > li:last-child { padding-bottom: 0; }

  /* ————————————————————–
    Tree labels
  */
  .tree_label {
    position: relative;
    display: inline-block;
    }

  label.tree_label { cursor: pointer; }

  label.tree_label:hover { color: #666; }

  /* ————————————————————–
    Tree expanded icon
  */
  label.tree_label:before {
    background: #000;
    color: #fff;
    position: relative;
    z-index: 1;
    float: left;
    margin: 0 1em 0 -2em;
    width: 1em;
    height: 1em;
    border-radius: 1em;
    content: '+';
    text-align: center;
    line-height: .9em;
    }

  :checked ~ label.tree_label:before { content: '–'; }

  /* ————————————————————–
    Tree branches
  */
  .tree li:before {
    position: absolute;
    top: 0;
    bottom: 0;
    left: -.5em;
    display: block;
    width: 0;
    border-left: 1px solid #777;
    content: "";
    }

  .tree_label:after {
    position: absolute;
    top: 0;
    left: -1.5em;
    display: block;
    height: 0.5em;
    width: 1em;
    border-bottom: 1px solid #777;
    border-left: 1px solid #777;
    border-radius: 0 0 0 .3em;
    content: '';
    }

  label.tree_label:after { border-bottom: 0; }

  :checked ~ label.tree_label:after {
    border-radius: 0 .3em 0 0;
    border-top: 1px solid #777;
    border-right: 1px solid #777;
    border-bottom: 0;
    border-left: 0;
    bottom: 0;
    top: 0.5em;
    height: auto;
    }

  .tree li:last-child:before {
    height: 1em;
    bottom: auto;
    }

  .tree > li:last-child:before { display: none; }

  .tree_custom {
    display: block;
    background: #eee;
    padding: 1em;
    border-radius: 0.3em;
  }

  ul {
    list-style-type:none
  }

  input.ambiguous {
    position: relative;
  }

app/views/interaction_claims/_interaction_search_successful.html.haml
- definite_matches = definite_results + definite_no_interactions
%div{style: "float: right; margin-top: -15px; width: 20%"}
  = render partial: 'shared/page_export'
  %div.alert.alert-error.well{style: "margin-top: 15px; padding-right: 20px; width: 200px;"}
    %h3{style: "margin-top: -5px;"}
      Preset Filters
    %ul
    - [@preset_fda, @preset_neo, @preset_immuno, @preset_clin, @preset_resist, @preset_druggable].reject { |c| c.empty? }.each do |preset|
      %li
        = preset

  %div.well{style: "margin-top: -5px; padding-right: 20px; width: 200px;"}
    %h3{style: "margin-top: -5px;"}
      Unique Matches
    %div
    - if definite_matches.count > 0
      - definite_matches.each do |result|
        %div
        - result[:identifiers].each do |entity|
          %input{class: "unique sidebar-toggle", type: "checkbox", name: "#{entity.name + "-unique"}", checked: 1}
            = "Search Term: " + result[:term]
    - else
      %i 
        None found.

%div{style: "float: left; width: 78%;"}
  %ul(class="result-list" id="list-results")
    - if definite_matches.count > 0
      - definite_matches.each do |result|
        - result[:identifiers].each do |entity|
          %li{class: "interaction interaction-panel", "data-category" => "interaction", "data-name" => "Interaction", id: entity.name + "-unique", style: "width: 100%;"}
            = render partial: 'interaction_claims/interactions_search_panel', locals: { term: result[:term], entity: entity, filtered_interactions: result[:interactions][entity].to_a }
    - else 
      %li{class: "interaction interaction-panel", "data-category" => "interaction", "data-name" => "Interaction", style: "width: 100%; height: 300px;"}
        %h3{style: "margin-left: 20px;"}
          None of your search terms returned 
          %i 
            unique 
          matches.

app/views/interaction_claims/_interaction_table_row.html.haml
%tr
  %td
    =interaction_table_row.search_term
  - if @search_mode == 'genes'
    %td{title: interaction_table_row.gene_name + ' - ' + interaction_table_row.gene_long_name, class: "truncate"}
      = link_to gene_path(interaction_table_row.gene_name) do
        %strong
          = interaction_table_row.gene_name.html_safe
        = " - "
        %em
          %small
            =interaction_table_row.gene_long_name.html_safe
    %td{title: interaction_table_row.drug_name}
      =link_to truncate(interaction_table_row.drug_name.html_safe, length:50), drug_path(interaction_table_row.drug_name)
    %td
      =link_to interaction_table_row.types_string, interaction_claims_path(interaction_table_row.interaction_claim)
    %td
      = interaction_table_row.source_link
    %td{style: 'display:none;'}
      = interaction_table_row.gene_name
    %td{style: 'display:none;'}
      = interaction_table_row.gene_long_name
    %td{style: 'display:none;'}
      = interaction_table_row.source_db_version
  - else
    %td{title: interaction_table_row.drug_name, class: "truncate"}
      = link_to drug_path(interaction_table_row.drug_name) do
        %strong
          = interaction_table_row.drug_name.html_safe
    %td{title: interaction_table_row.gene_name + ' - ' + interaction_table_row.gene_long_name, class: "truncate"}
      =link_to gene_path(interaction_table_row.gene_name) do
        = interaction_table_row.gene_name.html_safe
        = " - "
        %em
          %small
            =interaction_table_row.gene_long_name.html_safe
    %td
      =link_to interaction_table_row.types_string, interaction_claims_path(interaction_table_row.interaction_claim)
    %td
      = interaction_table_row.source_link
    %td{style: 'display:none;'}
      = interaction_table_row.drug_name
    %td{style: 'display:none;'}
      = interaction_table_row.source_db_version
  %td
    =interaction_table_row.pmids.map { |p| p.value.strip }.join(', ')
  -# TODO: Figure out why adding this breaks sorting on the "By Source" page.

app/views/interaction_claims/_interactions_search_panel.html.haml
- if @search_mode == "genes" 
  - entity = GenePresenter.new(entity)
- else
  - entity = DrugPresenter.new(entity)

%div(class="item-title")
  %div(class="item-name")
    %h3(class="item-source")
      %span
        = "Search Term: " + "\"" + term + "\""
      %span{class: "glyphicon glyphicon-play", "aria-hidden" => "true", style: "margin-left: 10px; margin-right: -8px"}
      &nbsp
      - if @search_mode == "genes"
        %a{href: "/genes/#{entity.name}#_interactions"}
          = entity.name
      - else
        %a{href: "/drugs/#{entity.name}#_interactions"}
          = entity.name

%div(class="item-content")
  %div(class="cell category")
    %div{class: "item-panel"}
      %h4{style: "display: inline-block;"}
      - interactions = filtered_interactions.sort_by { |i| -i.sources.size - i.publications.size }.map{|i| InteractionPresenter.new(i)}
      - if interactions.count > 0
        %table{class: "search_panel table table-condensed table-striped", style: "width: 100%; margin-top: -20px;"}
          %tr
            %th
              - if @search_mode == "genes"
                Drug
              - else
                Gene
            %th
              Interaction Type
            %th
              Sources
            %th
              PMIDs
            %th
              Score
          %tbody
          - interactions.each do |interaction|
            %tr{onclick: "location.href='/interactions/#{interaction.id}';"}
              %td
                - if @search_mode == "genes"
                  %a{href: "/drugs/#{interaction.drug.name}"}
                    = interaction.drug.name
                - else
                  %a{href: "/genes/#{interaction.gene.name}"}
                    = interaction.gene.name
              %td
                = interaction.na_or_types.join(", ")
              %td
                - source_count = interaction.sources.size
                = interaction.sources.map{|source| TrustLevelPresenter.source_link_green(@view_context, source)}.join(' ').html_safe
              %td
                - if (pub_count = interaction.publications.size) > 0
                  = interaction.publications.map{|pub| pubmed_link_blue(pub.pmid)}.join(" ").html_safe
                - else
                  %i
                    None found
              %td
                = source_count + pub_count
        %button{class: "show-all", style: "margin-top: 5px"}
          Show All
        %button{class: "show-more", style: "margin-top: 5px"}
          Show More
        %button{class: "show-less", style: "margin-top: 5px"}
          Show Less
        %span{style: "display: inline-block; margin-top: 5px; margin-left: 5px"}
          Showing
          %span#nrows
            = [10, interactions.length].min
          %span
            = "out of #{interactions.length} Interactions"
      - else
        No interactions found.

:css
  tr:hover td{
    background-color:rgba(220, 220, 220, 1);
    cursor: pointer;
  }
  td .label {
    display: inline-block;
    margin-bottom: 3px;
  }

app/views/interaction_claims/_no_interaction_result.html.haml
.span6
  .well
    %p
      %h3
        =title
        %small
          %strong
            %i.icon-flag.tip{title: tooltip_text}
      %small
        %strong
          %em
            =subtitle
    %dl
      -results.each do |result|
        -result.identifiers.each do |id|
          -if result.type == 'genes'
            %dt=link_to id.name, gene_path(id.name)
          -else
            %dt=link_to id.name, drug_path(id.name)
          %dd="For search term: #{result.search_term}"

app/views/interaction_claims/_results_by_drug_table.html.haml
.row-fluid
  .span12
    .well
      %h3 
        Results Summarized by Drug
        %small
          %strong
            %i.icon-flag.tip{title: tx("search_results_by_drug_flag")}
      %small
        %strong
          %em Gene interaction count associated with each drug.
      %p
      =render partial: 'shared/table_export', locals: {id: 'table-by-drug'}
      %table#table-by-drug.table.table-striped.table-bordered{cellpadding: "0", cellspacing: "0", border: "0"}
        %thead
          %tr
            %th 
              Search Term
              %i.icon-flag.tip{title: tx("search_term_table_header_flag")}
            %th 
              Drug
              %i.icon-flag.tip{title: tx("drug_table_header_flag")}
            %th 
              Distinct Gene Count
              %i.icon-flag.tip{title: tx("interaction_by_drug_table_header_distinct_gene_count_flag")}
        %tbody
          =render partial: 'interaction_claims/results_by_drug_table_row', collection: results.interactions_by_drug

app/views/interaction_claims/_results_by_drug_table_row.html.haml
%tr
  %td
    =results_by_drug_table_row.search_term
  %td{title: results_by_drug_table_row.drug_name, class: "truncate"}
    = link_to drug_path(results_by_drug_table_row.drug_name) do
      %strong
        = results_by_drug_table_row.drug_name
  %td
    =results_by_drug_table_row.gene_count

app/views/interaction_claims/_results_by_gene_table.html.haml
.row-fluid
  .span12
    .well
      %h3 
        Results Summarized by Gene
        %small
          %strong
            %i.icon-flag.tip{title: tx("search_results_by_gene_flag")}
      %small
        %strong
          %em Drug interaction count and druggable categories associated with each gene.
      %p
      =render partial: 'shared/table_export', locals: {id: 'table-by-gene'}
      %table#table-by-gene.table.table-striped.table-bordered{cellpadding: "0", cellspacing: "0", border: "0"}
        %thead
          %tr
            %th 
              Search Term
              %i.icon-flag.tip{title: tx("search_term_table_header_flag")}
            %th 
              Gene
              %i.icon-flag.tip{title: tx("gene_table_header_flag")}
            %th 
              Distinct Drug Count
              %i.icon-flag.tip{title: tx("interaction_by_gene_table_header_distinct_drug_count_flag")}
            %th
              Druggable Gene Categories
              %i.icon-flag.tip{title: tx("interaction_by_gene_table_header_druggable_categories_flag")}
        %tbody
          =render partial: 'interaction_claims/results_by_gene_table_row', collection: results.interactions_by_gene

app/views/interaction_claims/_results_by_gene_table_row.html.haml
%tr
  %td
    =results_by_gene_table_row.search_term
  %td{title: results_by_gene_table_row.gene_name + ' - ' + results_by_gene_table_row.gene_display_name, class: "truncate"}
    = link_to gene_path(results_by_gene_table_row.gene_name) do
      %strong
        = results_by_gene_table_row.gene_name
      = " - "
      %em
        %small{ class: "truncate" }
          =results_by_gene_table_row.gene_display_name
  %td
    =results_by_gene_table_row.drug_count
  %td
    =(results_by_gene_table_row.category_list.map{|g| link_to g, gene_by_category_path(g)}).join(', ').html_safe

app/views/interaction_claims/_results_by_source_table.html.haml
.row-fluid
  .span12
    .well
      %h3 
        Results Summary
        %small
          %strong
            %i.icon-flag.tip{title: tx("search_results_by_source_flag")}
      %small
        %strong
          %em Drug-gene interactions summarized by the source(s) that reported them.
      %p
      =render partial: 'shared/table_export', locals: {id: 'table-by-source'}
      %table#table-by-source.table.table-striped.table-bordered(cellpadding="0" cellspacing="0" border="0")
        %thead
          %tr
            %th 
              Interaction
              %i.icon-flag.tip{title: tx("interaction_by_source_table_header_interaction_flag")}
            -results.source_db_names_for_table.each do |name|
              %th{title: name}=name.gsub(/[a-z]/,'')[0..1]
            %th
              Sources
              %i.icon-flag.tip{title: tx("interaction_by_source_table_header_count_flag")}
            %th
              PMID
              %i.icon-flag.tip{title: tx("interaction_by_source_table_pmid_count_flag")}
            %th
              Score
        %tbody
          =render partial: 'interaction_claims/results_by_source_table_row', collection: results.interactions_map_by_source_db_names